"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var api_product_1 = require("./api.product");
exports.productApi = api_product_1.default;
var api_upload_1 = require("./api.upload");
exports.uploadApi = api_upload_1.default;
var api_saiheSync_1 = require("./saihe/api.saiheSync");
exports.transportApi = api_saiheSync_1.default;
var api_getSaiheTransportWays_1 = require("./saihe/api.getSaiheTransportWays");
exports.transportWays = api_getSaiheTransportWays_1.default;
